-- Migration: Phase 12 optional document intelligence
--
-- Adds a reviewable document_insights table and the analyze_document worker
-- job type. Document intelligence is optional and runs only in the worker:
-- clients enqueue jobs through existing agent_jobs RLS, while the worker
-- inserts draft insights with the service role key. Photos/images are not
-- analyzed by this migration or by the Phase 12 worker code.

alter type public.job_type add value if not exists 'analyze_document';

create table public.document_insights (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  document_id uuid not null references public.documents (id) on delete cascade,
  title text not null,
  summary text not null,
  key_points jsonb not null default '[]'::jsonb,
  suggested_actions jsonb not null default '[]'::jsonb,
  source text not null default 'ai',
  review_state text not null default 'ai_draft',
  created_by uuid references public.profiles (id) on delete set null,
  created_by_job_id uuid references public.agent_jobs (id) on delete set null,
  reviewed_by uuid references public.profiles (id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_insights_review_state_check check (
    review_state in ('ai_draft', 'approved', 'edited', 'rejected')
  ),
  constraint document_insights_source_check check (source in ('ai', 'human')),
  constraint document_insights_key_points_array_check check (jsonb_typeof(key_points) = 'array'),
  constraint document_insights_suggested_actions_array_check check (
    jsonb_typeof(suggested_actions) = 'array'
  )
);

comment on table public.document_insights is
  'Reviewable document intelligence drafts generated by the worker from text-only document content.';
comment on column public.document_insights.document_id is
  'Project document analyzed by the worker. Phase 12 accepts text-like documents only.';
comment on column public.document_insights.key_points is
  'Reviewable array of key points extracted from text content.';
comment on column public.document_insights.suggested_actions is
  'Reviewable array of human follow-up actions suggested from text content.';
comment on column public.document_insights.created_by_job_id is
  'Agent job that generated this insight; used for provenance and idempotent retries.';
comment on column public.document_insights.review_state is
  'Review workflow state: ai_draft, approved, edited or rejected.';

create unique index document_insights_created_by_job_id_idx
  on public.document_insights (created_by_job_id)
  where created_by_job_id is not null;
create index document_insights_project_document_idx
  on public.document_insights (project_id, document_id, created_at desc);
create index document_insights_project_review_state_idx
  on public.document_insights (project_id, review_state);

create trigger document_insights_set_updated_at
  before update on public.document_insights
  for each row execute function public.set_updated_at();

-- Explicit Data API grants: newer Supabase projects can opt out of automatic
-- grants. RLS below still decides which rows authenticated users may access.
revoke all on table public.document_insights from anon, authenticated, service_role;
grant select, update on table public.document_insights to authenticated;
grant select, insert, update, delete on table public.document_insights to service_role;

alter table public.document_insights enable row level security;

-- Members can read document insights for their own projects.
create policy "document_insights: select members"
  on public.document_insights for select
  to authenticated
  using (public.is_project_member(project_id));

-- Editors review generated drafts through normal RLS-scoped web actions.
-- UPDATE needs both USING and WITH CHECK so a row cannot be moved into
-- another project. There is no authenticated INSERT policy: insights are
-- generated only by the worker. There is no authenticated DELETE policy:
-- review history is preserved.
create policy "document_insights: update editors"
  on public.document_insights for update
  to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));
