-- Migration: Phase 8 weekly summaries
--
-- Weekly summaries are generated by the worker from text-only project data and
-- reviewed by humans in the web app. The worker uses the service role key, so
-- the table intentionally has no client INSERT policy.

create table public.weekly_summaries (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  week_start date not null,
  week_end date not null,
  title text not null,
  summary text not null,
  review_state text not null default 'ai_draft',
  source text not null default 'ai',
  created_by uuid references public.profiles (id) on delete set null,
  created_by_job_id uuid references public.agent_jobs (id) on delete set null,
  reviewed_by uuid references public.profiles (id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weekly_summaries_date_order_check check (week_start <= week_end),
  constraint weekly_summaries_review_state_check check (
    review_state in ('ai_draft', 'approved', 'edited', 'rejected')
  ),
  constraint weekly_summaries_source_check check (source in ('ai', 'human'))
);

comment on table public.weekly_summaries is
  'Reviewable weekly project summaries generated by the worker from text-only inputs.';
comment on column public.weekly_summaries.created_by_job_id is
  'Agent job that generated this summary; used for provenance and idempotent retries.';
comment on column public.weekly_summaries.review_state is
  'Review workflow state: ai_draft, approved, edited or rejected.';

create unique index weekly_summaries_created_by_job_id_idx
  on public.weekly_summaries (created_by_job_id)
  where created_by_job_id is not null;
create index weekly_summaries_project_week_idx
  on public.weekly_summaries (project_id, week_start desc, week_end desc);
create index weekly_summaries_project_review_state_idx
  on public.weekly_summaries (project_id, review_state);

create trigger weekly_summaries_set_updated_at
  before update on public.weekly_summaries
  for each row execute function public.set_updated_at();

-- Explicit Data API grants: newer Supabase projects can opt out of automatic
-- grants. RLS below still decides which rows authenticated users may access.
revoke all on table public.weekly_summaries from anon, authenticated, service_role;
grant select, update on table public.weekly_summaries to authenticated;
grant select, insert, update, delete on table public.weekly_summaries to service_role;

alter table public.weekly_summaries enable row level security;

-- Members can read weekly summaries for their own projects.
create policy "weekly_summaries: select members"
  on public.weekly_summaries for select
  to authenticated
  using (public.is_project_member(project_id));

-- Editors review AI drafts through normal web server actions. UPDATE needs
-- both USING and WITH CHECK so a row cannot be moved into another project.
create policy "weekly_summaries: update editors"
  on public.weekly_summaries for update
  to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

-- No authenticated INSERT policy: weekly summaries are generated only by the
-- worker. No authenticated DELETE policy: review history is preserved.
